# Netlify configuration for proxying API requests to avoid CORS issues
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/reddit/*"
  to = "https://www.reddit.com/:splat"
  status = 200
  force = true
